export { default as ArrowIcon } from './arrow'
export { default as ClockIcon } from './clock'
export { default as HomeOffice } from './home-office' 
export { default as Workshops } from './workshop'
export { default as FruitIcon } from './fruitsIcon' 
